# Generated by Django 4.2.13 on 2024-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_users_otp_users_otp_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
