# Generated by Django 4.2.13 on 2024-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_alter_users_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="max_otp_try",
            field=models.IntegerField(default=3),
        ),
    ]
